[project]
name = "docker_status"
version = "0.1.0"
description = "Flask web-app displaying Docker container status"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["flask", "gunicorn", "docker"]
